# Generated by Django 4.1.7 on 2023-02-28 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.simple_chat.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simple_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='participants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, validators=[apps.simple_chat.validators.validate_participants_count]),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread', to='simple_chat.thread'),
        ),
    ]
