# Generated by Django 4.1.7 on 2023-03-01 01:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simple_chat', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='MessageModel',
        ),
        migrations.RenameModel(
            old_name='Thread',
            new_name='ThreadModel',
        ),
    ]
