# Generated by Django 4.1.7 on 2023-03-01 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simple_chat', '0004_alter_threadmodel_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadmodel',
            name='participants',
            field=models.ManyToManyField(related_name='participants_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
